### ISSUE TITLE
Registro de Reunião - 08/06/2020 - 14h a 15h

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/Selecoes#18]
**Encaminhamentos anteriores** (Issue https://github.com/EscolaDeSaudePublica/Selecoes/issues/11)
- [ ] (@helenhilario ) Marcar reunião com o **Ares** (https://github.com/EscolaDeSaudePublica/Selecoes/issues/12)
- [x] (@victorMagalhaesPacheco ) Implementar o login (keycloak) para o mapas/seleções (https://github.com/EscolaDeSaudePublica/Selecoes/issues/13)
- [ ] (@Junior-Shyko ) Relatório das funcionalidades **Mapas vs Seleções**, que já foi iniciada (https://github.com/EscolaDeSaudePublica/Selecoes/issues/14)
- [ ] (@rmadev-master ) Mapear funcionalidades dos sistemas de **cadastro de pessoas, eventos, seleções e eventos científicos** que ainda não estão no Mapas (https://github.com/EscolaDeSaudePublica/Selecoes/issues/15)
- [ ] (@rmadev-master @victorMagalhaesPacheco RafaelMapas) Fazer o DER integrado com o Mapas (https://github.com/EscolaDeSaudePublica/Selecoes/issues/16)
- [x] (@rmadev-master ) Relatório de tipos de documentos solicitados (https://github.com/EscolaDeSaudePublica/Selecoes/issues/17)

**Pauta**

- Seleções atuais e seleções futuras;
- Eventos pequenos/Certificados;
- Mapas.

**Comment by rafaelmassuncao** [comment]
Encaminhamentos:

**1.** Configuração do keycloak/mapas (@victorMagalhaesPacheco ): (https://github.com/EscolaDeSaudePublica/Selecoes/issues/20)
- [ ] Testar biblioteca (https://github.com/stevenmaguire/oauth2-keycloak);
- [ ] Criar plugin específico;
- [ ] Publicar e testar funcionamento.

**2.** Fazer planilha comparativa de funções das Seleções (atual) (@rmadev-master e, caso preciso, @Junior-Shyko ) para comparativo ao Mapas. (https://github.com/EscolaDeSaudePublica/Selecoes/issues/21)

**3.** Reunião do GTCESP para amanhã (@helenhilario ). (https://github.com/EscolaDeSaudePublica/Selecoes/issues/19)

**4.** Criar modelo/planilha no Google para impressão de Certificados de participantes (@rmadev-master ). (https://github.com/EscolaDeSaudePublica/Selecoes/issues/22)

**5.** Assistir vídeo de apresentação do Mapas: :cinema: [clique aqui](https://www.youtube.com/watch?v=Rk5N-Mv3-VQ&feature=youtu.be)

**Comment by rafaelmassuncao** [comment]
Link para o Mapas: https://mapacultural.secult.ce.gov.br/
Mapas (Casa Civil): https://politicaspublicas.casacivil.ce.gov.br/
