### ISSUE TITLE
Edital de professor visitante, da Adins (data a prever)

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/Selecoes#31]
**Atividades:**

- [x] Atualizar mapas implantado (homologações/testes) (https://github.com/EscolaDeSaudePublica/Selecoes/issues/32) @Junior-Shyko 
- [x] Reuniões de planejamento e testes
- [x] Criação de oportunidades e avaliando os candidatos
- [x] Testes de inscrições (agentes)
- [x] Demonstração do sistema para o GTCESP (Edital 03/2020 usado como base)
- [ ] Criar edital de testes para que as pessoas das áreas possam testar o uso (https://github.com/EscolaDeSaudePublica/Selecoes/issues/34)
- [ ] Definição de cronograma de implantação
- [x] Mapas implantado (homologação/testes pra GTCESP) : https://devmapas.esp.ce.gov.br/
(https://github.com/EscolaDeSaudePublica/Selecoes/issues/33)
- [ ] Mapas implantado (máquina Rafael Moreira) (https://github.com/EscolaDeSaudePublica/Selecoes/issues/35)
- [x] Realização de testes de execução e cadastro de editais
- [ ] Testes aprovados pelo GTCESP
- [ ] Possíveis correções resolvidas
- [ ] Possíveis adições ao projeto resolvidas
- [ ] Mapas implantado (produção) : Mudar endereço para https://mapa.saude.ce.gov.br/
- [ ] Divulgação do Mapas nas redes
- [ ] Execução do Edital no sistema

**Comment by rafaelmassuncao** [comment]
Ambiente de testes: https://devmapas.esp.ce.gov.br/ (cancelado para testes)

**Comment by rafaelmassuncao** [comment]
Ambiente de testes: https://aldirblanc.mapasculturais.com.br/
