### ISSUE TITLE
Edital 14/2021 - CEATS

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/Selecoes#84]
### Objetivo
**Como** candidato de processo seletivo
**Quando** acessar o endereço de inscrições do Edital nº 14/2021 - CEATS
**Então** quero realizar minha inscrição e participar de todas as etapas das quais for classificado dentro do processo.

### Escopo
O edital precisa estar no ar no dia 20/08/2021 conforme especificado.

<table border="1" align="center">
<thead>
  <tr>
    <td colspan="2"><strong>Acompanhamento do Edital</strong></td>
  </tr>
</thead>
<body>
  <tr>
    <td>GitHub</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/projects/42">clique aqui</a></td>
  </tr>
  <tr>
    <td>Trello</td>
    <td><a href="#">não cadastrado</a></td>
  </tr>
  <tr>
    <td>Página da ESP-CE</td>
    <td><a href="">aguardando</a></td>
  </tr>
  <tr>
    <td>Endereço do Sistema</td>
    <td><a href="">aguardando</a></td>
  </tr>
</body>
</table>

**Critérios de Aceitação:** 
- [x] Edital analisado (calendário, etapas, pontuação, etc) 
- [x] Edital criado no Sisweb/SIGRH :point_left:
- [x] Criada a estrutura de banco
- [x] Implementado e testado
- [x] Publicado 

<table border="1" align="center">
<thead>
  <tr>
    <td colspan="2"><strong>Links das Issues dos Critérios de Aceitação</strong></td>
  </tr>
</thead>
<body>
  <tr>
    <td>Análise do edital (calendário, etapas, pontuação, etc)</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/272">clique aqui</a></td>
  </tr>
  <tr>
    <td>Criar o edital do Sisweb/SIGRH</td>
     <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/273">clique aqui</a></td>
  </tr>
  <tr>
    <td>Criar a estrutura de banco</td>
     <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/274">clique aqui</a></td>
  </tr>
  <tr>
    <td>Implementar e testar</td>
      <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/275">clique aqui</a></td>
  </tr>
  <tr>
    <td>Publicar o edital</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/276">clique aqui</a></td>
  </tr>
</body>
</table>

**Comment by luannaalves** [comment]
Edital analisado, apto a ser criado no Sisweb/SIGRH.
